-- Infinity Workspace :: baseline schema (MySQL 8.0+)
--
-- Consolidated from the original PostgreSQL migration set. Notes on the translation:
--   * Identifiers are CHAR(36) UUIDs generated by the application, so an insert already
--     knows its own id and does not need PostgreSQL's RETURNING.
--   * PostgreSQL arrays (text[]) become JSON arrays; membership tests use JSON_CONTAINS
--     and JSON_CONTAINS. Deliberately no multi-valued indexes and no JSON_OVERLAPS:
--     both are MySQL 8.0.17+ and absent from MariaDB, and this schema installs on both.
--   * timestamptz becomes DATETIME(3) holding UTC. The driver is pinned to UTC so a
--     value round-trips unchanged; DATETIME avoids TIMESTAMP's 2038 ceiling.
--   * Partial indexes have no MySQL equivalent, so the predicate is dropped and the
--     index covers the whole column. Uniqueness that depended on a predicate is
--     reproduced with a generated column instead.

-- =============================================================== tenancy
CREATE TABLE companies (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  name             VARCHAR(200) NOT NULL,
  verified_domains JSON         NOT NULL,
  region           VARCHAR(40)  NOT NULL DEFAULT 'primary',
  status           VARCHAR(20)  NOT NULL DEFAULT 'active',
  settings         JSON         NOT NULL,
  created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT companies_status_chk CHECK (status IN ('active','suspended'))
) ENGINE=InnoDB;

CREATE TABLE departments (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  company_id CHAR(36)     NOT NULL,
  name       VARCHAR(160) NOT NULL,
  parent_id  CHAR(36)     NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY departments_company_name (company_id, name),
  CONSTRAINT departments_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT departments_parent_fk FOREIGN KEY (parent_id) REFERENCES departments(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- =============================================================== identity
CREATE TABLE users (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  company_id    CHAR(36)     NOT NULL,
  email         VARCHAR(320) NOT NULL,
  email_display VARCHAR(320) NOT NULL,
  display_name  VARCHAR(160) NOT NULL,
  legal_name    VARCHAR(200) NULL,
  title         VARCHAR(160) NULL,
  department_id CHAR(36)     NULL,
  manager_id    CHAR(36)     NULL,
  access_level  VARCHAR(20)  NOT NULL DEFAULT 'staff',
  status        VARCHAR(20)  NOT NULL DEFAULT 'invited',
  locale        VARCHAR(16)  NOT NULL DEFAULT 'en',
  timezone      VARCHAR(64)  NOT NULL DEFAULT 'UTC',
  phone         VARCHAR(40)  NULL,
  avatar_color  VARCHAR(16)  NOT NULL DEFAULT '#f2c14e',
  modules       JSON         NOT NULL,
  version       INT          NOT NULL DEFAULT 1,
  suspended_at  DATETIME(3)  NULL,
  activated_at  DATETIME(3)  NULL,
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY users_company_email (company_id, email),
  KEY users_company_status (company_id, status),
  KEY users_department (department_id),
  CONSTRAINT users_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT users_department_fk FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
  CONSTRAINT users_manager_fk FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT users_access_level_chk CHECK (access_level IN
    ('super_admin','admin','manager','staff','auditor','guest','service')),
  CONSTRAINT users_status_chk CHECK (status IN ('invited','active','suspended','offboarded'))
) ENGINE=InnoDB;

-- Credentials are isolated from the profile row.
CREATE TABLE identities (
  user_id          CHAR(36)     NOT NULL PRIMARY KEY,
  password_hash    TEXT         NULL,
  password_algo    VARCHAR(20)  NOT NULL DEFAULT 'scrypt',
  password_set_at  DATETIME(3)  NULL,
  provider         VARCHAR(60)  NULL,
  provider_subject VARCHAR(200) NULL,
  mfa_enabled      TINYINT(1)   NOT NULL DEFAULT 0,
  mfa_secret_enc   TEXT         NULL,
  mfa_confirmed_at DATETIME(3)  NULL,
  recovery_codes   JSON         NOT NULL,
  failed_attempts  INT          NOT NULL DEFAULT 0,
  locked_until     DATETIME(3)  NULL,
  last_auth_at     DATETIME(3)  NULL,
  updated_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT identities_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE invitations (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  company_id CHAR(36)     NOT NULL,
  user_id    CHAR(36)     NOT NULL,
  token_hash VARCHAR(64)  NOT NULL,
  expires_at DATETIME(3)  NOT NULL,
  used_at    DATETIME(3)  NULL,
  created_by CHAR(36)     NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY invitations_token (token_hash),
  KEY invitations_user (user_id),
  CONSTRAINT invitations_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT invitations_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT invitations_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE sessions (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  company_id    CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  token_hash    VARCHAR(64)  NOT NULL,
  csrf_secret   VARCHAR(128) NOT NULL,
  mfa_satisfied TINYINT(1)   NOT NULL DEFAULT 0,
  device        VARCHAR(160) NULL,
  ip            VARCHAR(45)  NULL,
  user_agent    VARCHAR(400) NULL,
  expires_at    DATETIME(3)  NOT NULL,
  revoked_at    DATETIME(3)  NULL,
  last_seen_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY sessions_token (token_hash),
  KEY sessions_user (user_id),
  CONSTRAINT sessions_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE api_tokens (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  company_id   CHAR(36)     NOT NULL,
  user_id      CHAR(36)     NOT NULL,
  name         VARCHAR(160) NOT NULL,
  token_hash   VARCHAR(64)  NOT NULL,
  capabilities JSON         NOT NULL,
  expires_at   DATETIME(3)  NULL,
  revoked_at   DATETIME(3)  NULL,
  last_used_at DATETIME(3)  NULL,
  created_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY api_tokens_token (token_hash),
  CONSTRAINT api_tokens_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT api_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =============================================================== authorization
CREATE TABLE role_capabilities (
  role       VARCHAR(20) NOT NULL,
  capability VARCHAR(60) NOT NULL,
  PRIMARY KEY (role, capability)
) ENGINE=InnoDB;

CREATE TABLE `groups` (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  company_id  CHAR(36)     NOT NULL,
  name        VARCHAR(160) NOT NULL,
  description VARCHAR(500) NULL,
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY groups_company_name (company_id, name),
  CONSTRAINT groups_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE group_members (
  group_id CHAR(36)    NOT NULL,
  user_id  CHAR(36)    NOT NULL,
  role     VARCHAR(20) NOT NULL DEFAULT 'member',
  PRIMARY KEY (group_id, user_id),
  KEY group_members_user (user_id),
  CONSTRAINT group_members_group_fk FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE,
  CONSTRAINT group_members_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT group_members_role_chk CHECK (role IN ('member','owner'))
) ENGINE=InnoDB;

-- Explicit per-resource grants (membership/ownership authorization).
CREATE TABLE resource_grants (
  id            CHAR(36)    NOT NULL PRIMARY KEY,
  company_id    CHAR(36)    NOT NULL,
  subject_type  VARCHAR(10) NOT NULL,
  subject_id    CHAR(36)    NOT NULL,
  resource_type VARCHAR(40) NOT NULL,
  resource_id   CHAR(36)    NOT NULL,
  effect        VARCHAR(10) NOT NULL DEFAULT 'allow',
  capabilities  JSON        NOT NULL,
  conditions    JSON        NOT NULL,
  granted_by    CHAR(36)    NULL,
  expires_at    DATETIME(3) NULL,
  created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY grants_lookup (company_id, resource_type, resource_id),
  KEY grants_subject (subject_type, subject_id),
  CONSTRAINT grants_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT grants_granter_fk FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT grants_subject_type_chk CHECK (subject_type IN ('user','group')),
  CONSTRAINT grants_effect_chk CHECK (effect IN ('allow','deny'))
) ENGINE=InnoDB;

-- =============================================================== audit + outbox
CREATE TABLE audit_events (
  id             BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  company_id     CHAR(36)     NOT NULL,
  actor_id       CHAR(36)     NULL,
  actor_email    VARCHAR(320) NULL,
  action         VARCHAR(80)  NOT NULL,
  resource_type  VARCHAR(40)  NULL,
  resource_id    CHAR(36)     NULL,
  result         VARCHAR(10)  NOT NULL DEFAULT 'success',
  ip             VARCHAR(45)  NULL,
  user_agent     VARCHAR(400) NULL,
  correlation_id VARCHAR(64)  NULL,
  before_state   JSON         NULL,
  after_state    JSON         NULL,
  metadata       JSON         NOT NULL,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY audit_company_time (company_id, created_at DESC),
  KEY audit_actor (actor_id, created_at DESC),
  KEY audit_resource (resource_type, resource_id),
  CONSTRAINT audit_result_chk CHECK (result IN ('success','denied','error'))
) ENGINE=InnoDB;

-- Transactional outbox: db commit and emitted event cannot diverge.
CREATE TABLE outbox_events (
  id             BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  company_id     CHAR(36)    NOT NULL,
  type           VARCHAR(60) NOT NULL,
  version        INT         NOT NULL DEFAULT 1,
  payload        JSON        NOT NULL,
  actor_id       CHAR(36)    NULL,
  correlation_id VARCHAR(64) NULL,
  available_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  locked_at      DATETIME(3) NULL,
  attempts       INT         NOT NULL DEFAULT 0,
  processed_at   DATETIME(3) NULL,
  last_error     TEXT        NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY outbox_pending (processed_at, available_at)
) ENGINE=InnoDB;

CREATE TABLE dead_letters (
  id         BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source     VARCHAR(40) NOT NULL,
  payload    JSON        NOT NULL,
  error      TEXT        NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;

CREATE TABLE idempotency_keys (
  `key`               VARCHAR(200) NOT NULL,
  company_id          CHAR(36)     NOT NULL,
  user_id             CHAR(36)     NOT NULL,
  endpoint            VARCHAR(160) NOT NULL,
  request_fingerprint VARCHAR(64)  NOT NULL,
  status_code         INT          NULL,
  response            JSON         NULL,
  created_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`key`, company_id, endpoint)
) ENGINE=InnoDB;

CREATE TABLE rate_counters (
  bucket     VARCHAR(200) NOT NULL PRIMARY KEY,
  count      INT          NOT NULL DEFAULT 0,
  expires_at DATETIME(3)  NOT NULL
) ENGINE=InnoDB;

-- =============================================================== notifications
CREATE TABLE notifications (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  company_id    CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  type          VARCHAR(60)  NOT NULL,
  title         VARCHAR(300) NOT NULL,
  body          TEXT         NULL,
  link          VARCHAR(500) NULL,
  resource_type VARCHAR(40)  NULL,
  resource_id   CHAR(36)     NULL,
  dedupe_key    VARCHAR(200) NULL,
  read_at       DATETIME(3)  NULL,
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY notifications_user (user_id, created_at DESC),
  -- MySQL permits repeated NULLs in a unique key, which reproduces the PostgreSQL
  -- partial unique index on dedupe_key without needing the predicate.
  UNIQUE KEY notifications_dedupe (user_id, dedupe_key),
  CONSTRAINT notifications_company_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT notifications_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
